In [1]:
import tensorflow as tf

from tensorflow.keras import layers

In [2]:
# Initialising tensors of 0
zero_init=tf.zeros_initializer()
tensor_1=zero_init(shape=(2,3))
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [3]:
# Same as above
tf_zeros=tf.zeros((2,3))
tf_zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [4]:
# Random Normal initializer
random_init=tf.random_normal_initializer()
tensor_2=random_init((4,5))
tensor_2

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.00902745, -0.03056854, -0.07194978,  0.00245987,  0.02198003],
       [ 0.05937332, -0.00403734, -0.02727481,  0.06275862,  0.0086606 ],
       [ 0.02383982,  0.02031765, -0.0247496 , -0.03660399,  0.09084921],
       [ 0.10113718,  0.00522245,  0.03222394,  0.00604396, -0.03636928]],
      dtype=float32)>

In [5]:
# Same as above
tf_rand=tf.random.normal((4,5))
tf_rand

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.5550387 , -1.3227407 ,  0.10742939,  0.5754714 ,  2.6015885 ],
       [ 0.04821255,  1.9442492 ,  0.21065842,  0.42030582,  0.19040067],
       [-1.7112308 , -0.62808806, -0.53258026, -0.2225895 , -0.6429794 ],
       [ 2.9819388 , -0.7575359 , -2.2434952 , -1.0513608 ,  0.43877855]],
      dtype=float32)>

## Initializing a Simple Linear NN forward pass
Layer encapsulates state and the transformation from inputs to outputs

In [6]:
class SimpleLinear(layers.Layer):
    """
    SimpleLinear
    ------------------------------------
    Parameters :
    
    input_dims : the total number of input features
    units : total number of neurons in the layer
    
    """
    def __init__(self,input_dims=16,units=8,**kwargs):
        super(SimpleLinear,self).__init__(**kwargs)
        
        w_init=tf.random_normal_initializer()
        self.w=tf.Variable(initial_value=w_init(shape=(input_dims,units),
                                               dtype='float32'),
                          trainable=True)
        
        b_init=tf.zeros_initializer()
        self.b=tf.Variable(initial_value=b_init((units),dtype='float32'),
                          trainable=True)
        
    def call(self,input_tensors):
        return tf.matmul(input_tensors,self.w) +self.b

In [7]:
# Defining a random input tensor
x=tf.ones((4,3))
x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
layer1=SimpleLinear(input_dims=3,units=5)

y=layer1(x)

print(y)

tf.Tensor(
[[-0.03397065  0.2308265  -0.0325742   0.02061169 -0.05616296]
 [-0.03397065  0.2308265  -0.0325742   0.02061169 -0.05616296]
 [-0.03397065  0.2308265  -0.0325742   0.02061169 -0.05616296]
 [-0.03397065  0.2308265  -0.0325742   0.02061169 -0.05616296]], shape=(4, 5), dtype=float32)


In [9]:
# checking the weights
layer1.weights

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[ 0.0022761 ,  0.08788048,  0.03339681,  0.01799115,  0.02110327],
        [-0.06592079,  0.10671709,  0.00838614, -0.02669026, -0.02795597],
        [ 0.02967404,  0.03622892, -0.07435714,  0.02931081, -0.04931026]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [10]:
# Checking the trainable variables that prints both the weights and the 
# biases associated with the layers.
layer1.trainable_variables 

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[ 0.0022761 ,  0.08788048,  0.03339681,  0.01799115,  0.02110327],
        [-0.06592079,  0.10671709,  0.00838614, -0.02669026, -0.02795597],
        [ 0.02967404,  0.03622892, -0.07435714,  0.02931081, -0.04931026]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [11]:
# Checking the nontrainable variables and the losses associated with 
# each layer
layer1.non_trainable_variables

[]

In [12]:
layer1.losses

[]

## Method 2
Most of the times if the input features are not known to the user then we can initialise the model via this method

In [13]:
class SimpleLinear(layers.Layer):
    
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.units=units
        
    # During the forward pass, the layer will automatically call the build()
    # method to determine the shape of the inputs and initialize the weights
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer='zeros',
                              trainable=True)
        
    def call(self,input_tensor):
        return tf.matmul(input_tensor,self.w)+self.b

In [14]:
# Initializing input
random_uniform=tf.random_uniform_initializer()
x=random_uniform((4,5))
x

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.02411762, -0.03994356, -0.03458344,  0.03353811,  0.01433596],
       [-0.00023986,  0.00025884, -0.04324535,  0.03928411,  0.00372976],
       [ 0.02734495, -0.01007019, -0.02478502,  0.00704491, -0.01495076],
       [ 0.0127981 ,  0.02194271, -0.0378764 , -0.02696394, -0.03290088]],
      dtype=float32)>

In [15]:
# Initializing a class without the shape of the input variable
layers2=SimpleLinear(units=3)
y=layers2(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-1.4922817e-03,  4.5631924e-03, -8.5419957e-03],
       [ 9.4598045e-06,  1.8515445e-03, -6.1756135e-03],
       [ 7.3073042e-04,  9.8680716e-04, -2.1433735e-03],
       [ 2.2717128e-03, -3.5976470e-03,  3.3584146e-03]], dtype=float32)>

In [16]:
layers2.weights

[<tf.Variable 'simple_linear_1/Variable:0' shape=(5, 3) dtype=float32, numpy=
 array([[-0.06778654,  0.00639484, -0.01494635],
        [-0.04271008, -0.06950284,  0.0590882 ],
        [ 0.00300944,  0.01264456,  0.05634607],
        [ 0.01682263,  0.06149903, -0.08999886],
        [-0.14115177,  0.00052345, -0.05959132]], dtype=float32)>,
 <tf.Variable 'simple_linear_1/Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

## Initialising a Simple Linear NN with more than 1 layer forward pass

In [17]:
# Simple linear NN with 
class SimpleLinearBlock(layers.Layer):
    
    def __init__(self,block1_units=2,block2_units=4,block3_units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.linear_1=SimpleLinear(block1_units)
        self.linear_2=SimpleLinear(block2_units)
        self.linear_3=SimpleLinear(block3_units)
        
    def call(self,inputs):
        x=self.linear_1(inputs)
        x=tf.nn.relu(x)
        
        x=self.linear_2(x)
        x=tf.nn.relu(x)
        
        return self.linear_3(x)

In [18]:
# Instantiating the object of the class
simple_linear_block=SimpleLinearBlock()
y=simple_linear_block(x)
y

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.4656979e-06,  7.3210441e-07,  1.3714816e-06, -3.1525481e-06,
        -1.6354838e-06,  2.5373045e-06,  1.7343017e-06, -2.6770113e-06],
       [ 4.6346877e-06,  2.2813190e-06,  4.3640625e-06, -9.8525725e-06,
        -5.1009711e-06,  7.8948960e-06,  5.4317688e-06, -8.3710447e-06]],
      dtype=float32)>

In [19]:
# includes weights of each 
simple_linear_block.weights

[<tf.Variable 'simple_linear_block/simple_linear_2/Variable:0' shape=(5, 2) dtype=float32, numpy=
 array([[ 0.00919736,  0.05933924],
        [ 0.01814552,  0.06530889],
        [ 0.03996212, -0.01253904],
        [-0.04761524, -0.02249529],
        [-0.00035445, -0.02187215]], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_2/Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_3/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 2.0009888e-02, -8.3881030e-03,  3.1028295e-02,  7.6694683e-05],
        [ 1.2971694e-02, -1.2309920e-01,  1.6123127e-02, -3.7103418e-02]],
       dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_3/Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(4, 8) dtype=float32, numpy=
 array([[-0.00014113,  0.02275375, -0.01863571, -0.07840307, -0.0476979

In [20]:
# Computing loss associated with the forward pass
class RegularizationLoss(layers.Layer):
    def __init__(self,rate=1e-3,**kwargs):
        super().__init__(**kwargs)
        
        self.rate=rate
        
    # layers recursively collects errors from sub layers during forward loss   
    def call(self,inputs):
        self.add_loss(self.rate*tf.reduce_sum(inputs))
        
        return inputs

In [21]:
reg_loss_layer = RegularizationLoss()

y=reg_loss_layer(x)

y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.02411762, -0.03994356, -0.03458344,  0.03353811,  0.01433596],
       [-0.00023986,  0.00025884, -0.04324535,  0.03928411,  0.00372976],
       [ 0.02734495, -0.01007019, -0.02478502,  0.00704491, -0.01495076],
       [ 0.0127981 ,  0.02194271, -0.0378764 , -0.02696394, -0.03290088]],
      dtype=float32)>

In [22]:
# losses assciated with each layer is present in the losses
reg_loss_layer.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=-8.116433e-05>]

### Composing a Regularized layer with the Outer layer

In [23]:
class SimpleLinearRegularized(layers.Layer):
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        
        self.units=units
        self.reg=RegularizationLoss(1e-2)
        
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer='ones',
                              trainable=True)
        
    def call(self,input_tensors):
        output=tf.matmul(input_tensors,self.w) + self.b
        
        return self.reg(output)

In [24]:
# y is the same as the input x but there is a loss associated with it 
# which was previously 0
layers3=SimpleLinearRegularized(units=3)
y=layers3(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.99896306, 1.0027885 , 0.9961299 ],
       [1.0018696 , 1.0018736 , 0.99976254],
       [1.0014498 , 0.9995614 , 0.99870527],
       [1.0045989 , 0.99681866, 1.0020354 ]], dtype=float32)>

In [25]:
layers3.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.120045565>]

## Custom Dense Layer

In [26]:
class DenseRegularized(layers.Layer):
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.dense=layers.Dense(units,kernel_regularizer=tf.keras.regularizers.l2(1e-3))
        
        self.reg=RegularizationLoss(1e-2)
        
    def call(self,input_tensor):
        return self.reg(self.dense(input_tensor))

In [27]:
layer5=DenseRegularized(units=3)
y=layer5(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.01570651,  0.00987195, -0.00507249],
       [ 0.00013045,  0.0041152 ,  0.00858237],
       [-0.00616979,  0.0227704 ,  0.01035901],
       [-0.01472204,  0.04903283,  0.00925154]], dtype=float32)>

In [28]:
# 1st is the loss associated with the dense keras regularizer
# and 2nd is the loss associated with the custom loss
layer5.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.0031004439>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0010385594>]

## Serializing the Layer

In [29]:
class SimpleLinear(layers.Layer):
    
    def __init__(self,units=8,**kwargs):
        super(SimpleLinear,self).__init__(**kwargs)
        self.units=units
        
    # Helps with the weight initialization
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer = 'ones',
                              trainable=True)
        
        
    # Helps with the forward pass    
    def call(self,input_tensor):
        return tf.matmul(input_tensor,self.w)+self.b
    
    # Useful for Serializing the present Layer
    def get_config(self):
        config=super().get_config()
        config.update({'units':self.units})
        
        return config

In [30]:
layer6=SimpleLinear(units=3)
y=layer6(x)
print(y)

tf.Tensor(
[[1.000366   1.0042981  0.9952282 ]
 [1.0019532  1.0028276  0.99594784]
 [1.0005943  1.0041045  0.9989029 ]
 [1.0018231  1.0036355  1.000455  ]], shape=(4, 3), dtype=float32)


In [31]:
# Calling the get_config, and in our case we only specified the units
config=layer6.get_config()
config

{'name': 'simple_linear_5', 'trainable': True, 'dtype': 'float32', 'units': 3}

In [32]:
# Build a new layer with the same configuration
new_layer6=SimpleLinear.from_config(config)
print(new_layer6(x))

tf.Tensor(
[[1.0062287  1.0018716  1.0103018 ]
 [1.0029446  0.99729747 1.0096915 ]
 [1.0016078  1.0011208  1.003331  ]
 [0.99820125 1.0004576  1.0004061 ]], shape=(4, 3), dtype=float32)


## Dropout layer

In [33]:
class CustomDropout(layers.Layer):
    
    def __init__(self,rate,**kwargs):
        super(CustomDropout,self).__init__(**kwargs)
        self.rate=rate
        
    # needs additional parameter 'training' as the Dropout layer behaves
    # differently during training and testing.
    def call(self,inputs,training=None):
        if training:
            return tf.nn.dropout(inputs,rate=self.rate)
        
        return inputs

In [34]:
layer7=CustomDropout(rate=0.4)

print(layer7(x))

tf.Tensor(
[[ 0.02411762 -0.03994356 -0.03458344  0.03353811  0.01433596]
 [-0.00023986  0.00025884 -0.04324535  0.03928411  0.00372976]
 [ 0.02734495 -0.01007019 -0.02478502  0.00704491 -0.01495076]
 [ 0.0127981   0.02194271 -0.0378764  -0.02696394 -0.03290088]], shape=(4, 5), dtype=float32)


In [35]:
# Nothing happens above as we have training value as None/False
# Adding a dropout layer with training=True, by doing this we'll see
# that 40% of the data will now have 0 in place.
layer7_dropout=CustomDropout(rate=0.4)
print(layer7_dropout(x,training=True))

tf.Tensor(
[[ 0.04019604 -0.06657261 -0.05763906  0.05589684  0.        ]
 [-0.          0.0004314  -0.07207558  0.06547352  0.        ]
 [ 0.         -0.01678365 -0.04130836  0.         -0.02491794]
 [ 0.          0.03657118 -0.06312734 -0.         -0.        ]], shape=(4, 5), dtype=float32)


## Custom Regression Model

In [38]:
class CustomRegressionModel(tf.keras.Model):
    
    def __init__(self,input_shape,layer_units=[8,4],\
                activation='relu',initializer='random_normal'):
        super(CustomRegressionModel,self).__init__()
        assert len(layer_units)>0
        # input layer
        self.input_layer=layers.Dense(layer_units[0],activation='relu',
                                     kernel_initializer=initializer,
                                     input_shape=[input_shape])
        
        # hidden layers
        self.hidden_layers=[]
        
        for i in range(1,len(layer_units)):
            self.hidden_layers.append(layers.Dense(layer_units[i],
                                                  activation=activation,
                                                  kernel_initializer=initializer))
            
        # output layer with o/p 1 as it is a Regression problem
        self.output_layer=layers.Dense(1)
        
        
    # Forward pass via the call method
    def call(self,input_tensor):
        x=self.input_layer(input_tensor)
        
        for layer in self.hidden_layers:
            x=layer(x)
            
        result=self.output_layer(x)
        
        return result

In [37]:
# Creating a input
rand_uniform=tf.random_uniform_initializer()
x=rand_uniform(shape=(4,8))
x

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[-0.01629189, -0.01485084,  0.01104771,  0.01949776, -0.03587743,
        -0.01508524,  0.02445206, -0.04601003],
       [ 0.00577383, -0.0115394 ,  0.03660784,  0.02304305,  0.02786363,
         0.01227624,  0.00322606, -0.00215416],
       [-0.04443649, -0.03986238, -0.03464027, -0.046432  , -0.00904036,
         0.02792771, -0.04784675, -0.0184095 ],
       [-0.01544676,  0.02086978,  0.03126012, -0.02356156, -0.01701038,
        -0.02829906,  0.04033628,  0.00026138]], dtype=float32)>

In [39]:
# Creating an object for our Regression Class
# 3 layers that we have mentioned and the last one is the output layer
custom_reg_model=CustomRegressionModel(x.shape[-1],[8,16,32],'sigmoid')
custom_reg_model.layers

In [40]:
# Forward pass for the model, this is needed before we can print the summary 
# of the model. Output is the prediction made by the model.
custom_reg_model(x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.22642323],
       [-0.22642234],
       [-0.22641975],
       [-0.22642112]], dtype=float32)>

In [42]:
custom_reg_model.summary()

Model: "custom_regression_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              multiple                  72        
_________________________________________________________________
dense_2 (Dense)              multiple                  144       
_________________________________________________________________
dense_3 (Dense)              multiple                  544       
_________________________________________________________________
dense_4 (Dense)              multiple                  33        
Total params: 793
Trainable params: 793
Non-trainable params: 0
_________________________________________________________________


Goto the RegressionwithCustomLayer.ipynb for the implementation of Custom layer models on Dataset for Regression.