In [1]:
import tensorflow as tf

from tensorflow.keras import layers

In [4]:
# Initialising tensors of 0
zero_init=tf.zeros_initializer()
tensor_1=zero_init(shape=(2,3))
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [3]:
# Same as above
tf_zeros=tf.zeros((2,3))
tf_zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [5]:
# Random Normal initializer
random_init=tf.random_normal_initializer()
tensor_2=random_init((4,5))
tensor_2

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.01854942, -0.02042603, -0.04122335, -0.00379771,  0.02105224],
       [-0.01490488,  0.05142501, -0.06348874,  0.01774129,  0.09141453],
       [-0.03173401, -0.0306431 , -0.09838222,  0.00302464,  0.10726436],
       [-0.03961426, -0.02221404,  0.09078874, -0.00679971,  0.0684964 ]],
      dtype=float32)>

In [14]:
# Same as above
tf_rand=tf.random.normal((4,5))
tf_rand

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.46538264, -0.77688086, -0.22244208,  0.16578293, -1.5267727 ],
       [ 0.52710867,  0.9672521 , -2.6776025 , -0.5483236 , -0.9444202 ],
       [ 0.3775981 , -0.33004266, -1.1166155 ,  1.7185152 ,  0.66213363],
       [-0.54758584, -0.23892152, -0.8543801 ,  0.16094948,  0.07029601]],
      dtype=float32)>

## Initializing a Simple Linear NN forward pass
Layer encapsulates state and the transformation from inputs to outputs

In [15]:
class SimpleLinear(layers.Layer):
    """
    SimpleLinear
    ------------------------------------
    Parameters :
    
    input_dims : the total number of input features
    units : total number of neurons in the layer
    
    """
    def __init__(self,input_dims=16,units=8,**kwargs):
        super(SimpleLinear,self).__init__(**kwargs)
        
        w_init=tf.random_normal_initializer()
        self.w=tf.Variable(initial_value=w_init(shape=(input_dims,units),
                                               dtype='float32'),
                          trainable=True)
        
        b_init=tf.zeros_initializer()
        self.b=tf.Variable(initial_value=b_init((units),dtype='float32'),
                          trainable=True)
        
    def call(self,input_tensors):
        return tf.matmul(input_tensors,self.w) +self.b

In [16]:
# Defining a random input tensor
x=tf.ones((4,3))
x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
layer1=SimpleLinear(input_dims=3,units=5)

y=layer1(x)

print(y)

tf.Tensor(
[[ 0.11612452  0.0831324   0.00867198 -0.17072874  0.03786272]
 [ 0.11612452  0.0831324   0.00867198 -0.17072874  0.03786272]
 [ 0.11612452  0.0831324   0.00867198 -0.17072874  0.03786272]
 [ 0.11612452  0.0831324   0.00867198 -0.17072874  0.03786272]], shape=(4, 5), dtype=float32)


In [19]:
# checking the weights
layer1.weights

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[ 0.09040371, -0.011307  ,  0.04639702, -0.08460917,  0.02972027],
        [ 0.06540506,  0.04370268,  0.02127436, -0.00273685,  0.080735  ],
        [-0.03968426,  0.05073672, -0.05899939, -0.08338272, -0.07259255]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [20]:
# Checking the trainable variables that prints both the weights and the 
# biases associated with the layers.
layer1.trainable_variables 

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[ 0.09040371, -0.011307  ,  0.04639702, -0.08460917,  0.02972027],
        [ 0.06540506,  0.04370268,  0.02127436, -0.00273685,  0.080735  ],
        [-0.03968426,  0.05073672, -0.05899939, -0.08338272, -0.07259255]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [21]:
# Checking the nontrainable variables and the losses associated with 
# each layer
layer1.non_trainable_variables

[]

In [22]:
layer1.losses

[]

## Method 2
Most of the times if the input features are not known to the user then we can initialise the model via this method

In [28]:
class SimpleLinear(layers.Layer):
    
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.units=units
        
    # During the forward pass, the layer will automatically call the build()
    # method to determine the shape of the inputs and initialize the weights
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer='zeros',
                              trainable=True)
        
    def call(self,input_tensor):
        return tf.matmul(input_tensor,self.w)+self.b

In [29]:
# Initializing input
random_uniform=tf.random_uniform_initializer()
x=random_uniform((4,5))
x

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.02411537,  0.02215913,  0.01739193, -0.00579583, -0.01890131],
       [ 0.00329667, -0.04309945, -0.02772335, -0.02549037, -0.0420257 ],
       [-0.04146206,  0.01574183,  0.02732806,  0.00015129, -0.04524335],
       [ 0.03538409,  0.03085747, -0.0420269 , -0.01689041, -0.01858045]],
      dtype=float32)>

In [30]:
# Initializing a class without the shape of the input variable
layers2=SimpleLinear(units=3)
y=layers2(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.8026317e-03, -1.6588890e-03, -1.5355715e-04],
       [-3.8269411e-03, -4.4047125e-03, -1.1244778e-03],
       [ 7.1851083e-04, -6.3342601e-03, -2.7736407e-03],
       [-1.9031190e-03,  1.3972636e-03,  5.2133480e-05]], dtype=float32)>

In [31]:
layers2.weights

[<tf.Variable 'simple_linear_3/Variable:0' shape=(5, 3) dtype=float32, numpy=
 array([[ 0.02288637,  0.02370018,  0.03111989],
        [ 0.02198828,  0.02547281, -0.00939689],
        [ 0.06444674, -0.0463325 , -0.00267053],
        [ 0.02962834,  0.0195907 ,  0.02081271],
        [ 0.00982235,  0.09922734,  0.02797296]], dtype=float32)>,
 <tf.Variable 'simple_linear_3/Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

## Initialising a Simple Linear NN with more than 1 layer forward pass

In [38]:
# Simple linear NN with 
class SimpleLinearBlock(layers.Layer):
    
    def __init__(self,block1_units=2,block2_units=4,block3_units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.linear_1=SimpleLinear(block1_units)
        self.linear_2=SimpleLinear(block2_units)
        self.linear_3=SimpleLinear(block3_units)
        
    def call(self,inputs):
        x=self.linear_1(inputs)
        x=tf.nn.relu(x)
        
        x=self.linear_2(x)
        x=tf.nn.relu(x)
        
        return self.linear_3(x)

In [39]:
# Instantiating the object of the class
simple_linear_block=SimpleLinearBlock()
y=simple_linear_block(x)
y

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[-2.35732641e-05,  3.71008355e-05,  2.94589645e-05,
        -4.52627755e-05, -1.87013320e-05, -5.42344060e-05,
        -1.23551863e-05, -6.07437596e-06],
       [-1.77693964e-05,  3.75851523e-05,  2.19213125e-05,
        -3.43437750e-05, -2.31909908e-05, -3.93852533e-05,
        -9.39373604e-06, -4.93290145e-06],
       [-1.43909165e-05,  2.36535325e-05,  1.79542621e-05,
        -2.76553292e-05, -1.23662876e-05, -3.29525647e-05,
        -7.55094879e-06, -3.74522870e-06],
       [-7.52659071e-06,  1.48996842e-05,  9.31541581e-06,
        -1.45231461e-05, -8.85840018e-06, -1.68411480e-05,
        -3.97037365e-06, -2.05187439e-06]], dtype=float32)>

In [40]:
# includes weights of each 
simple_linear_block.weights

[<tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(5, 2) dtype=float32, numpy=
 array([[ 0.05401435,  0.06628237],
        [ 0.04976111, -0.01950275],
        [ 0.04748801,  0.06493761],
        [ 0.11685678, -0.07080941],
        [-0.04259014, -0.09224004]], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_5/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 0.04845412, -0.00450532, -0.07156083,  0.0553838 ],
        [ 0.01443342,  0.08587965, -0.00231978,  0.09044582]],
       dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_5/Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_6/Variable:0' shape=(4, 8) dtype=float32, numpy=
 array([[-0.08398646, -0.03705227, -0.04885611, -0.0585245 , -0.00252851,
         -0.09548997,

In [41]:
# Computing loss associated with the forward pass
class RegularizationLoss(layers.Layer):
    def __init__(self,rate=1e-3,**kwargs):
        super().__init__(**kwargs)
        
        self.rate=rate
        
    # layers recursively collects errors from sub layers during forward loss   
    def call(self,inputs):
        self.add_loss(self.rate*tf.reduce_sum(inputs))
        
        return inputs

In [42]:
reg_loss_layer = RegularizationLoss()

y=reg_loss_layer(x)

y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.02411537,  0.02215913,  0.01739193, -0.00579583, -0.01890131],
       [ 0.00329667, -0.04309945, -0.02772335, -0.02549037, -0.0420257 ],
       [-0.04146206,  0.01574183,  0.02732806,  0.00015129, -0.04524335],
       [ 0.03538409,  0.03085747, -0.0420269 , -0.01689041, -0.01858045]],
      dtype=float32)>

In [43]:
# losses assciated with each layer is present in the losses
reg_loss_layer.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=-0.00015081333>]

### Composing a Regularized layer with the Outer layer

In [44]:
class SimpleLinearRegularized(layers.Layer):
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        
        self.units=units
        self.reg=RegularizationLoss(1e-2)
        
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer='ones',
                              trainable=True)
        
    def call(self,input_tensors):
        output=tf.matmul(input_tensors,self.w) + self.b
        
        return self.reg(output)

In [45]:
# y is the same as the input x but there is a loss associated with it 
# which was previously 0
layers3=SimpleLinearRegularized(units=3)
y=layers3(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1.002293  , 0.99824136, 0.99779344],
       [1.0043979 , 1.0029004 , 1.0003469 ],
       [1.0051734 , 0.99598485, 1.0023541 ],
       [1.0042342 , 1.00008   , 1.0001353 ]], dtype=float32)>

In [46]:
layers3.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.120139346>]

## Custom Dense Layer

In [47]:
class DenseRegularized(layers.Layer):
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.dense=layers.Dense(units,kernel_regularizer=tf.keras.regularizers.l2(1e-3))
        
        self.reg=RegularizationLoss(1e-2)
        
    def call(self,input_tensor):
        return self.reg(self.dense(input_tensor))

In [48]:
layer5=DenseRegularized(units=3)
y=layer5(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.04110644, -0.03522261,  0.01494944],
       [-0.01633694,  0.03514275, -0.0403819 ],
       [-0.00127417,  0.02554684,  0.05603665],
       [-0.01683031, -0.01887583, -0.03015322]], dtype=float32)>

In [49]:
# 1st is the loss associated with the dense keras regularizer
# and 2nd is the loss associated with the custom loss
layer5.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.004529617>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.0006850575>]

## Serializing the Layer

In [59]:
class SimpleLinear(layers.Layer):
    
    def __init__(self,units=8,**kwargs):
        super(SimpleLinear,self).__init__(**kwargs)
        self.units=units
        
    # Helps with the weight initialization
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer = 'ones',
                              trainable=True)
        
        
    # Helps with the forward pass    
    def call(self,input_tensor):
        return tf.matmul(input_tensor,self.w)+self.b
    
    # Useful for Serializing the present Layer
    def get_config(self):
        config=super().get_config()
        config.update({'units':self.units})
        
        return config

In [60]:
layer6=SimpleLinear(units=3)
y=layer6(x)
print(y)

tf.Tensor(
[[1.0000958  0.9993271  0.99694   ]
 [1.0057142  0.99975365 0.9956415 ]
 [1.0036721  1.0008075  0.99835485]
 [1.0041668  1.0016233  0.99682945]], shape=(4, 3), dtype=float32)


In [61]:
# Calling the get_config, and in our case we only specified the units
config=layer6.get_config()
config

{'name': 'simple_linear_9', 'trainable': True, 'dtype': 'float32', 'units': 3}

In [64]:
# Build a new layer with the same configuration
new_layer6=SimpleLinear.from_config(config)
print(new_layer6(x))

tf.Tensor(
[[1.0021425  1.0014789  1.000758  ]
 [0.99211645 1.0009811  0.9934833 ]
 [0.9939109  0.9980058  1.004685  ]
 [1.0026059  1.0004336  0.99181134]], shape=(4, 3), dtype=float32)


## Dropout layer

In [67]:
class CustomDropout(layers.Layer):
    
    def __init__(self,rate,**kwargs):
        super(CustomDropout,self).__init__(**kwargs)
        self.rate=rate
        
    # needs additional parameter 'training' as the Dropout layer behaves
    # differently during training and testing.
    def call(self,inputs,training=None):
        if training:
            return tf.nn.dropout(inputs,rate=self.rate)
        
        return inputs

In [68]:
layer7=CustomDropout(rate=0.4)

print(layer7(x))

tf.Tensor(
[[ 0.02411537  0.02215913  0.01739193 -0.00579583 -0.01890131]
 [ 0.00329667 -0.04309945 -0.02772335 -0.02549037 -0.0420257 ]
 [-0.04146206  0.01574183  0.02732806  0.00015129 -0.04524335]
 [ 0.03538409  0.03085747 -0.0420269  -0.01689041 -0.01858045]], shape=(4, 5), dtype=float32)


In [69]:
# Nothing happens above as we have training value as None/False
# Adding a dropout layer with training=True, by doing this we'll see
# that 40% of the data will now have 0 in place.
layer7_dropout=CustomDropout(rate=0.4)
print(layer7_dropout(x,training=True))

tf.Tensor(
[[ 0.04019229  0.03693188  0.02898655 -0.00965971 -0.03150219]
 [ 0.         -0.         -0.         -0.04248394 -0.        ]
 [-0.          0.02623638  0.04554677  0.         -0.        ]
 [ 0.05897349  0.05142912 -0.07004483 -0.02815068 -0.03096741]], shape=(4, 5), dtype=float32)
