In [1]:
import tensorflow as tf

from tensorflow.keras import layers

In [2]:
# Initialising tensors of 0
zero_init=tf.zeros_initializer()
tensor_1=zero_init(shape=(2,3))
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [3]:
# Random Normal initializer
random_init=tf.random_normal_initializer()
tensor_2=random_init((4,5))
tensor_2

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.07875424,  0.02862801,  0.02349875, -0.04076311,  0.09593913],
       [-0.05641333,  0.05068347, -0.00706676,  0.08815709,  0.02787144],
       [-0.07833166, -0.01491617, -0.01577976,  0.00647235,  0.0213961 ],
       [ 0.0131471 , -0.05908561, -0.02372928, -0.03818778, -0.02568976]],
      dtype=float32)>

## Initializing a Simple Linear NN forward pass
Layer encapsulates state and the transformation from inputs to outputs

In [9]:
class SimpleLinear(layers.Layer):
    """
    SimpleLinear
    ------------------------------------
    Parameters :
    
    input_dims : the total number of input features
    units : total number of neurons in the layer
    
    """
    def __init__(self,input_dims=16,units=8,**kwargs):
        super(SimpleLinear,self).__init__(**kwargs)
        
        w_init=tf.random_normal_initializer()
        self.w=tf.Variable(initial_value=w_init(shape=(input_dims,units),
                                               dtype='float32'),
                          trainable=True)
        
        b_init=tf.zeros_initializer()
        self.b=tf.Variable(initial_value=b_init((units),dtype='float32'),
                          trainable=True)
        
    def call(self,input_tensors):
        return tf.matmul(input_tensors,self.w) +self.b

In [5]:
# Defining a random input tensor
x=tf.ones((4,3))
x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
layer1=SimpleLinear(input_dims=3,units=5)

y=layer1(x)

print(y)

tf.Tensor(
[[ 0.09334454 -0.21001208 -0.07709382 -0.14670528 -0.02168956]
 [ 0.09334454 -0.21001208 -0.07709382 -0.14670528 -0.02168956]
 [ 0.09334454 -0.21001208 -0.07709382 -0.14670528 -0.02168956]
 [ 0.09334454 -0.21001208 -0.07709382 -0.14670528 -0.02168956]], shape=(4, 5), dtype=float32)


In [11]:
# checking the weights
layer1.weights

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[ 0.06066642, -0.09583402, -0.00462387, -0.07891755, -0.03680738],
        [-0.00682286, -0.04210091, -0.00573193, -0.02192286,  0.04349955],
        [ 0.03950098, -0.07207714, -0.06673803, -0.04586487, -0.02838173]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [13]:
# Checking the trainable variables that prints both the weights and the 
# biases associated with the layers.
layer1.trainable_variables 

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[ 0.06066642, -0.09583402, -0.00462387, -0.07891755, -0.03680738],
        [-0.00682286, -0.04210091, -0.00573193, -0.02192286,  0.04349955],
        [ 0.03950098, -0.07207714, -0.06673803, -0.04586487, -0.02838173]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [15]:
# Checking the nontrainable variables and the losses associated with 
# each layer
layer1.non_trainable_variables

[]

In [16]:
layer1.losses

[]

## Method 2
Most of the times if the input features are not known to the user then we can initialise the model via this method

In [17]:
class SimpleLinear(layers.Layer):
    
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.units=units
        
    # During the forward pass, the layer will automatically call the build()
    # method to determine the shape of the inputs and initialize the weights
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer='ones',
                              trainable=True)
        
    def call(self,input_tensor):
        return tf.matmul(input_tensor,self.w)+self.b

In [18]:
# Initializing input
random_uniform=tf.random_uniform_initializer()
x=random_uniform((4,5))
x

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.03480405,  0.01608697,  0.0406068 , -0.0213593 ,  0.0476276 ],
       [-0.01846316, -0.00538139, -0.01598612,  0.047495  , -0.0034514 ],
       [-0.01717346,  0.01498104, -0.0374863 ,  0.02571664, -0.03202453],
       [-0.03247237, -0.04975696,  0.0196632 ,  0.00270705, -0.00151449]],
      dtype=float32)>

In [19]:
# Initializing a class without the shape of the input variable
layers2=SimpleLinear(units=3)
y=layers2(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.99928796, 1.003997  , 1.0009859 ],
       [1.007087  , 0.99948615, 0.99897224],
       [1.0049851 , 0.9990752 , 0.9992404 ],
       [1.0022165 , 0.9998303 , 0.9996735 ]], dtype=float32)>

## Initialising a Simple Linear NN with more than 1 layer forward pass

In [22]:
# Simple linear NN with 
class SimpleLinearBlock(layers.Layer):
    
    def __init__(self,block1_units=2,block2_units=4,block3_units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.linear_1=SimpleLinear(block1_units)
        self.linear_2=SimpleLinear(block2_units)
        self.linear_3=SimpleLinear(block3_units)
        
    def call(self,inputs):
        x=self.linear_1(inputs)
        x=tf.nn.relu(x)
        
        x=self.linear_2(x)
        x=tf.nn.relu(x)
        
        return self.linear_3(x)

In [23]:
# Instantiating the object of the class
simple_linear_block=SimpleLinearBlock()
y=simple_linear_block(x)
y

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[1.122722  , 1.0677923 , 0.95541364, 1.0099798 , 0.9330473 ,
        1.1277748 , 1.0638983 , 0.99970555],
       [1.1227192 , 1.0677736 , 0.9553949 , 1.0100209 , 0.9329959 ,
        1.1278129 , 1.0639204 , 0.99966896],
       [1.1227196 , 1.0677698 , 0.9553929 , 1.0100329 , 0.9329893 ,
        1.1278172 , 1.0639251 , 0.9996704 ],
       [1.1227316 , 1.067765  , 0.9554087 , 1.0100839 , 0.93302083,
        1.1277869 , 1.0639334 , 0.999764  ]], dtype=float32)>

In [24]:
# includes weights of each 
simple_linear_block.weights

[<tf.Variable 'simple_linear_block_1/simple_linear_5/Variable:0' shape=(5, 2) dtype=float32, numpy=
 array([[ 0.04144261, -0.06126549],
        [-0.04471121,  0.00444007],
        [ 0.0218251 , -0.09040137],
        [-0.00020006,  0.05664685],
        [-0.07753924, -0.0098432 ]], dtype=float32)>,
 <tf.Variable 'simple_linear_block_1/simple_linear_5/Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>,
 <tf.Variable 'simple_linear_block_1/simple_linear_6/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.02710937,  0.05976055, -0.13947542,  0.05927534],
        [ 0.06308769, -0.01811245, -0.02209657, -0.06563155]],
       dtype=float32)>,
 <tf.Variable 'simple_linear_block_1/simple_linear_6/Variable:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Variable 'simple_linear_block_1/simple_linear_7/Variable:0' shape=(4, 8) dtype=float32, numpy=
 array([[-0.00443919,  0.03368673, -0.03452427, -0.03290294, -0.0666955 ,
          0

In [26]:
# Computing loss associated with the forward pass
class RegularizationLoss(layers.Layer):
    def __init__(self,rate=1e-3,**kwargs):
        super().__init__(**kwargs)
        
        self.rate=rate
        
    # layers recursively collects errors from sub layers during forward loss   
    def call(self,inputs):
        self.add_loss(self.rate*tf.reduce_sum(inputs))
        
        return inputs

In [27]:
reg_loss_layer = RegularizationLoss()

y=reg_loss_layer(x)

y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.03480405,  0.01608697,  0.0406068 , -0.0213593 ,  0.0476276 ],
       [-0.01846316, -0.00538139, -0.01598612,  0.047495  , -0.0034514 ],
       [-0.01717346,  0.01498104, -0.0374863 ,  0.02571664, -0.03202453],
       [-0.03247237, -0.04975696,  0.0196632 ,  0.00270705, -0.00151449]],
      dtype=float32)>

In [29]:
# losses assciated with each layer is present in the losses
reg_loss_layer.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=-5.498923e-05>]

### Composing a Regularized layer with the Outer layer

In [38]:
class SimpleLinearRegularized(layers.Layer):
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        
        self.units=units
        self.reg=RegularizationLoss(1e-2)
        
    def build(self,input_shape):
        self.w=self.add_weight(shape=(input_shape[-1],self.units),
                              initializer='random_normal',
                              trainable=True)
        
        self.b=self.add_weight(shape=(self.units),
                              initializer='ones',
                              trainable=True)
        
    def call(self,input_tensors):
        output=tf.matmul(input_tensors,self.w) + self.b
        
        return self.reg(output)

In [39]:
# y is the same as the input x but there is a loss associated with it 
# which was previously 0
layers3=SimpleLinearRegularized(units=3)
y=layers3(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1.0021824 , 1.0045875 , 1.0034289 ],
       [1.0045444 , 0.9948639 , 0.9975855 ],
       [0.99964345, 0.99552417, 0.99516165],
       [1.0093046 , 0.99675864, 1.0019703 ]], dtype=float32)>

In [40]:
layers3.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.12005554>]

## Custom Dense Layer

In [42]:
class DenseRegularized(layers.Layer):
    def __init__(self,units=8,**kwargs):
        super().__init__(self,**kwargs)
        self.dense=layers.Dense(units,kernel_regularizer=tf.keras.regularizers.l2(1e-3))
        
        self.reg=RegularizationLoss(1e-2)
        
    def call(self,input_tensor):
        return self.reg(self.dense(input_tensor))

In [43]:
layer5=DenseRegularized(units=3)
y=layer5(x)
y

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.03367104, -0.00389524, -0.04225908],
       [ 0.01779637, -0.03489458, -0.02151488],
       [ 0.04149149, -0.03704301,  0.0076455 ],
       [-0.03262861,  0.00650179, -0.04980633]], dtype=float32)>

In [44]:
# 1st is the loss associated with the dense keras regularizer
# and 2nd is the loss associated with the custom loss
layer5.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.0033388846>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.0018227763>]